"""empty message

Revision ID: 957b22160eee
Revises: ed23f8aa11b4
Create Date: 2021-04-30 11:38:35.737925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '957b22160eee'
down_revision = 'ed23f8aa11b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('completed', sa.Boolean(), nullable=True))
    
    op.execute('UPDATE todos SET completed = False WHERE completed IS NULL;')
    
    op.alter_column('todos','completed',nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'completed')
    # ### end Alembic commands ###
